### PR TITLE
Add popup menu

### PR DESCRIPTION
**Pull request by zawnk**
This is the very first time I'm coding something related to a Chrome extension, so I googled a lot of stuff and 90% of my code is quick and dirty but gets the job done. 

I've added a popup menu that lists the 10 newest unread items with title, source and icon. You can either click on the title to open the link in a new tab and mark it as read or click the X to remove it from the list and mark it as read. 

As I said, it's not pretty and probably far from optimized, but I was about to fork the original Repo and add this menu, when I saw your fork, much appreciated!

Another small change: I've added a small trailing slash check in the options, since I did that wrong and it took me a while to figure out. A better approach would be to sanitize user input and just correct it for them automatically before saving, but that's up to you.

Edit: If you want you can join the [Hacktoberfest](https://hacktoberfest.digitalocean.com/) with this project to maybe boost the PRs a bit :) Or if you don't want to do that, you could label this PR with 'hacktoberfest-accepted' so it counts towards my progress, thanks :)

Edit2: I've now noticed a delay when opening the popup, probably due to me fetching the entries and then the fav icons of each feed (~50ms per call according to postman).  
Instead of fetching it on click, it would probably be smarter to cache all the feed icons in localStorage, or even better, run the functions in the background regularly and cache the whole list in localStorage and when opening the popup, just fetch the date from there.

### CODE REVIEW

**Comment by vdrandom** [comment]
Sorry, for some reason I have missed the notification.

I'm most likely way less skilled with js than you are. I'll check your pull request as soon as I can. Probably overdue for the hacktoberfest though. :<

**Comment by vdrandom** [comment]
So far looks good, but I'm conflicted about two things: the delay you have mentioned as well as the way it looks.

Not that I have any right to complain about the looks considering how much of a mess the settings menu is.

**Comment by zawnk** [comment]
Yep, fully agree with both points. The delay is not really noticeable to me anymore. It's very minimal, but to be fair, the instance is hosted in my LAN. I can see it getting annoying when the miniflux is hosted remotely. But I've suggested approaches on how to fix that behavior.

And yeah, feel completely free to overhaul any design aspect of this. I just wanted a list menu for months if not years, so I finally did it quick and dirty. I've been using it daily since I've opened this PR 5 weeks ago and it's serving its perfectly. I haven't noticed any bug or anything not working. I can manage my unread list completely from the popup and that's exactly what I wanted.

If I have some time in the near future I might be enhancing some of the functionality or work with the localStorage cache so that the delay when opening the menu is gone, but pretty busy right now. Don't hesitate to implement some of the functionality because you're waiting for me!

And thanks for merging!

**Comment by vdrandom** [comment]
Feel free to submit any improvements (use popup-v2 branch please), I'll pay more attention to emails from github. :)

I'll see if I find time to learn more js in the meantime. :)

**Pull request merged**
